Feature/choose languange and currency
maxCopell/tripadvisor-scraper pull request #31
Opened 2021-05-30 14:40 UTC by gustavotr

Fix issue #24

Depends on #30

2021-06-16 19:24 UTC, pocesar commented
hey @gustavotr can you merge both PRs into one? they will conflict since some of the code is being changed in both PRs. or should only this one be prioritized?

2021-06-16 21:09 UTC, gustavotr commented
Sure, I will fix this one and cancel the other one.

2021-06-17 08:39 UTC, gustavotr commented
@pocesar done

2021-06-18 17:49 UTC, pocesar commented on INPUT_SCHEMA.json
> +      "type": "number",
need to set the `editor` here and for `maxItems` to `number` (and the type being `integer`)

2021-06-23 04:40 UTC, pocesar requested changes
nitpick: I can't test on the platform while the INPUT schema is invalid

2021-06-23 04:40 UTC, pocesar commented on INPUT_SCHEMA.json
> +  "required": [
while you're at it, exchange this array to `["proxyConfiguration"]` only

2021-06-23 04:40 UTC, pocesar commented on src/main.js
> +    const currency = input.currency || 'CZK';
default should be `'USD'`

2021-06-23 04:40 UTC, pocesar commented on INPUT_SCHEMA.json
> +      "editor": "select",
place the `default` and `prefill` to `USD`

2021-06-25 18:02 UTC, pocesar commented
I'm going to merge this, but need to fix some issues, the user agent is giving away that it's using axios, as I can't run this on the platform properly

2021-06-25 18:02 UTC, merged